DROP TABLE IF EXISTS PECA_CONDICIONAL;
DROP TABLE IF EXISTS VENDA_PECA;
DROP TABLE IF EXISTS COMPRA_PECA;
DROP TABLE IF EXISTS PECA;
DROP TABLE IF EXISTS CONDICIONAL;
DROP TABLE IF EXISTS VENDA;
DROP TABLE IF EXISTS CLIFISICO;
DROP TABLE IF EXISTS CLIJURIDICO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS VENDEDOR;
DROP TABLE IF EXISTS ADM;
DROP TABLE IF EXISTS FUNCIONARIO;

CREATE TABLE FUNCIONARIO (
	idFunc INTEGER		PRIMARY KEY,
	nome VARCHAR(500),
	sexo VARCHAR(20),
    salario DECIMAL(10,2),
    dataN DATE,
    cpf INTEGER,
    telefone INTEGER
);

CREATE TABLE ADM (
	id INTEGER		PRIMARY KEY,
    FOREIGN KEY(id) REFERENCES FUNCIONARIO(idFunc) ON DELETE CASCADE
);

CREATE TABLE VENDEDOR (
	id INTEGER		PRIMARY KEY,
	comissão DECIMAL(10,2), 
    nivelDoVendedor VARCHAR(100),
    tempoDeServiço INTEGER, 
	FOREIGN KEY(id) REFERENCES FUNCIONARIO (idFunc) ON DELETE CASCADE
);

CREATE TABLE FORNECEDOR (
	idFornecedor INTEGER	PRIMARY KEY,
	cnpj INTEGER,
	nome VARCHAR(500),
	telefone INTEGER
);

CREATE TABLE COMPRA (
	idCompra INTEGER	PRIMARY KEY,
    dataCompra DATE,
    precoT DECIMAL(10,2),
    idFornecedor INTEGER	NOT NULL,
    idADM INTEGER	NOT NULL,
    FOREIGN KEY (idFornecedor) REFERENCES FORNECEDOR (idFornecedor),
    FOREIGN KEY (idADM) REFERENCES ADM (id)
);

CREATE TABLE CLIENTE (
	idCliente INTEGER	PRIMARY KEY,
    sexo VARCHAR(20),
    dataNasc DATE,
    nome VARCHAR(500),
    telefone INTEGER
);

CREATE TABLE CLIJURIDICO (
	id INTEGER		PRIMARY KEY,
    cnpj INTEGER,
    razaoSocial VARCHAR(500),
    siteEmpresa VARCHAR(500),
    FOREIGN KEY (id) REFERENCES CLIENTE (idCliente) ON DELETE CASCADE
);

CREATE TABLE CLIFISICO (
	id INTEGER		PRIMARY KEY,
    cpf INTEGER,
    emal VARCHAR(500),
    apelido VARCHAR(100),
    FOREIGN KEY (id) REFERENCES CLIENTE (idCliente) ON DELETE CASCADE
);

CREATE TABLE VENDA (
	idVenda INTEGER 	PRIMARY KEY,
    preçoT DECIMAL(10,2),
    dataVenda DATE,
    idFun INTEGER  	NOT NULL,
    idCli INTEGER 	NOT NULL,
    FOREIGN KEY (idFun) REFERENCES VENDEDOR (id),
    FOREIGN KEY (idCli) REFERENCES CLIENTE (idCliente)
);

CREATE TABLE CONDICIONAL (
	idCond INTEGER		PRIMARY KEY,
    qtde INTEGER,
    descricao VARCHAR(500),
    preco DECIMAL(10,2),
    idCli INTEGER  NOT NULL,
    FOREIGN KEY (idCli) REFERENCES CLIENTE (idCliente)
);

CREATE TABLE PECA (
	descricao VARCHAR(500)		PRIMARY KEY,
    qtdePeca INTEGER,
    preco DECIMAL(10,2)
);

CREATE TABLE COMPRA_PECA (
	idC INTEGER,
    descricao VARCHAR(500),
     PRIMARY KEY(idC, descricao),
    FOREIGN KEY (idC) REFERENCES COMPRA (idCompra),
    FOREIGN KEY (descricao) REFERENCES PECA (descricao)
);

CREATE TABLE VENDA_PECA (
	idV INTEGER,
    descricao VARCHAR(500),
    PRIMARY KEY(idV, descricao),
    FOREIGN KEY (idV) REFERENCES VENDA (idVenda),
	FOREIGN KEY (descricao) REFERENCES PECA (descricao)
);

CREATE TABLE PECA_CONDICIONAL (
	id INTEGER,
	descricao VARCHAR(500),
	PRIMARY KEY(id, descricao),
    FOREIGN KEY (id) REFERENCES CONDICIONAL (idCond),
    FOREIGN KEY (descricao) REFERENCES PECA (descricao)
);